export const mockProducts = [
  {
    id: '101',
    name: 'Mung Bean Mild Acidic Cleansing Foam',
    brand: 'beplain',
    category: 'Cleansing Foam',
    price: 9.51,
    originalPrice: 10.98,
    discount: '13% Off',
    reviews: 3.5,
    rating: null,
    image: 'https://skin-seoul.com/wp-content/uploads/2024/05/thu_100004626_1-1.webp',
    isAdded: false,
    count: 0,
    wishlists: [],
  },
  {
    id: '102',
    name: 'Mung Bean Pore Clay Pack 120ml',
    brand: 'beplain',
    category: 'Face Mask',
    price: 16.91,
    originalPrice: 25.52,
    discount: '34% Off',
    reviews: 4.1,
    rating: 4.7,
    image: 'https://skin-seoul.com/wp-content/uploads/2024/05/thu_100002163_1-1.webp',
    isAdded: false,
    count: 0,
    wishlists: [],
  },
  {
    id: '103',
    name: 'Water Sleeping Mask EX',
    brand: 'LANEIGE',
    category: 'Sleeping Mask',
    price: 65.67,
    originalPrice: 89.06,
    discount: '13% Off',
    reviews: 7.8,
    rating: 5,
    image: 'https://skin-seoul.com/wp-content/uploads/2024/05/thu_100007210_1-1.webp',
    isAdded: false,
    count: 0,
    wishlists: [],
  },
  {
    id: '104',
    name: 'Aqua Squalane Moisturizing Cream',
    brand: 'S.NATURE',
    category: 'Moisturizer',
    price: 22.94,
    originalPrice: 29.91,
    discount: '23% Off',
    reviews: 5,
    rating: 3.7,
    image: 'https://skin-seoul.com/wp-content/uploads/2024/05/thu_100004668_1-1.webp',
    isAdded: false,
    count: 0,
    wishlists: [],
  },
  {
    id: '105',
    name: 'Waterfull Fresh Sun Cushion',
    brand: "d'Alba",
    category: 'Moisturizer',
    price: 33.94,
    originalPrice: 29.91,
    discount: '23% Off',
    reviews: 6,
    rating: 4.7,
    image: 'https://skin-seoul.com/wp-content/uploads/2024/05/thu_100004867_1-1.webp',
    isAdded: false,
    count: 0,
    wishlists: [],
  },
  {
    id: '106',
    name: 'Clear Face Spa Lip and Eye Remover',
    brand: "POND'S",
    category: 'Moisturizer',
    price: 16.0,
    originalPrice: 29.91,
    discount: '23% Off',
    reviews: 10,
    rating: 4.7,
    image: 'https://skin-seoul.com/wp-content/uploads/2024/05/thu_100004950_1-1.webp',
    isAdded: false,
    count: 0,
    wishlists: [],
  },
];
