import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

// import "./globals.css";
import "./reset.css";
import { SSDesignSystemProvider } from "@/styles/SSDesignSystemProvider";
import { QueryProvider } from "@/providers/QueryProvider";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--plus-jakarta-sans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Chakra Ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakartaSans.className}>
      <body>
        <SSDesignSystemProvider>
          <QueryProvider>{children}</QueryProvider>
        </SSDesignSystemProvider>
      </body>
    </html>
  );
}
